---
- name: Install gcc
  ansible.builtin.package:
    name: gcc
    state: present

- name: Fetch Go and unpack it to /usr/local/go
  ansible.builtin.unarchive:
    src: https://dl.google.com/go/go1.15.7.linux-amd64.tar.gz
    dest: /usr/local/
    remote_src: yes
  tags:
    - go_download

- name: Set GOPATH for all users
  copy:
    src: go_path.sh
    dest: /etc/profile.d
