---
# TODO: add local go version checking later
#- name: Get go version
#  command: go version
# changed_when: false
#  check_mode: false
#  register: __go_version
#  delegate_to: localhost
#  tags:
#    - go_version
- name: Fetch Go and unpack it to /usr/local/go
  ansible.builtin.unarchive:
    src: https://dl.google.com/go/go1.15.7.linux-amd64.tar.gz
    dest: /usr/local/
    remote_src: yes
  delegate_to: localhost
  tags:
    - go_download

- name: Set GOPATH for all users
  copy:
    src: go_path.sh
    dest: /etc/profile.d
