---
- name: install the latest Go version on localhost
  import_tasks: go_install.yml
  tags: install_go_local

- name: install the latest Go version on the target host
  import_tasks: go_install_remote.yml
  tags: install_go_remote

- name: setup nginx and certbot and letsencrypt
  import_tasks: setup-nginx.yaml
  become: true
  tags: nginx_proxy

- name: compile validator locally and deploy it to the target host
  import_tasks: install.yml
  become: true
  tags: localhost_build

- name: compile validator on remote target host
  import_tasks: remote_compile.yml
  become: true
  tags: remote_host_build

- name: configure the validator and run init 
  import_tasks: validator_init.yml
  become: true
  become_method: su
  become_user: nym
  become_flags: '-s /bin/sh'
  become_exe: 'sudo su -'
  vars:
    ansible_shell_allow_world_readable_temp: true
  tags: validator_init

- name: run validator with systemd 
  import_tasks: validator_run.yml
  become: true
  tags: validator_run
